name: Compilar

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Descomprimir proyecto
        run: |
          unzip "*.zip" -d proyecto
          find proyecto -name gradlew -exec chmod +x {} \;

      - name: Preparar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Compilar APK debug
        run: |
          cd $(dirname $(find proyecto -name gradlew | head -n 1))
          ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-debug
          path: proyecto/**/app/build/outputs/apk/debug/*.apk
